### ISSUE TITLE
Missing initialization in DemoClassic example

### ISSUE THREAD

**Issue by jeanpierrefortune** [eclipse/keyple-cpp#12]
Branch 0.8.1
The SecuritySettings field is not initialized here : https://github.com/eclipse/keyple-cpp/blob/2914ac40917c77362e3afd2a2d1a90adf28a1537/example/calypso/common/src/main/transaction/CalypsoClassicTransactionEngine.cpp#L54

Should be
`CalypsoClassicTransactionEngine::securitySettings = std::make_shared<SecuritySettings>();`

**Comment by al3xwq** [comment]
Fixed and pushed to feat/develop-0.8.1.
