### ISSUE TITLE
Useless file headers and namespaces in examples

### ISSUE THREAD

**Issue by jeanpierrefortune** [eclipse/keyple-cpp#14]
The example code should not have to import low-level plugin definitions.

For example, in Demo_CalypsoClassic_Pcsc.cpp you can remove : 
```
#include "PcscPluginImpl.h"
#include "PcscReaderImpl.h"
using namespace keyple::core::seproxy::plugin::local;
```
It is then necessary to change
```
    /* Set the default selection operation */
    (std::dynamic_pointer_cast<PcscReaderImpl>(poReader))
        ->setDefaultSelectionRequest(
```
into
```
    /* Set the default selection operation */
    (std::dynamic_pointer_cast<ObservableReader>(poReader))
        ->setDefaultSelectionRequest(

```

**Comment by al3xwq** [comment]
Good spot. Remains from back in the days when casts to ObservalReader were not possible :-) I'll clean that up.

**Comment by al3xwq** [comment]
commit 810f3f84059e3adf4096d0e8d192eb52f704b855 (HEAD -> feat/develop-0.8.1, origin/feat/develop-0.8.1)
Author: Alexandre MUNSCH <alexandre.munsch@gmail.com>
Date:   Wed May 6 23:41:53 2020 +0200

    fix: keyple-cpp-14 Useless file headers and namespaces in examples
    Removed useless header files in examples and fixed bad casts coming
    along with them.
    
    Signed-off-by: Alexandre MUNSCH <alexandre.munsch@gmail.com>
