### ISSUE TITLE
Example7 and Example8 SVGet command Le fixed at 00

### ISSUE THREAD

**Issue by cabalona** [eclipse/keyple-cpp#36]
I am using a Rev3.1, T=0 card and I am getting error at line 121 of SVGetRespPars.cpp as Le is fixed at 00

When I change the Le to the correct value:
21h for Reload, without SV Serial Number request. 
1Eh for Debit or Undebit, without SV Serial Number request. 

Both examples 7 and 8 finish without errors.

May I ask if in ex7 and ex8, should the Le be always fixed to 00?

**Comment by jeanpierrefortune** [comment]
Hello,
Indeed, these are "type 4" commands (incoming/outgoing) for which Le=0 is not allowed in contact mode.
Can you tell us more about your context of use of keyple c++?
You should know in particular that a version 2.0 is about to be released. It brings a number of improvements.
See [keyple-cpp-meta 2.0](https://github.com/eclipse/keyple-cpp-meta)
Anyway, changing the values of Le may help to make the existing code work in 1.0 but you may encounter other difficulties elsewhere.
Regards

**Comment by cabalona** [comment]
Hi,
Thanks for your reply. We are using the keyple C++ to try to run simple contactless transactions (e.g. reload and debit) between a PCSC reader, Calypso CL card rev 3.1, and SAM-C1. 

In both examples, Le is always fixed to 0. I did the changes to the code. 

I look forward to the 2.0 version then.

Thanks and best regards.
