### ISSUE TITLE
Make Problems

### ISSUE THREAD

**Issue by kadirkidir1** [eclipse/keyple-cpp#38]
Hi, i'm trying to make this project. I run sudo cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain/gcc-linux.cmake .. command and created makefile. But after when i try to "make" command, i receive some error.

**In file included from /home/XXXX/keyple-cpp/component/keyple-calypso/src/main/transaction/PoTransaction.cpp:29:
/home/XXXX/keyple-cpp/component/keyple-calypso/src/main/transaction/exception/CalypsoPoCloseSecureSessionException.h: In member function ‘const keyple::calypso::command::po::exception::CalypsoPoCommandException& keyple::calypso::transaction::exception::CalypsoPoCloseSecureSessionException::getCause()’:
/home/XXXX/keyple-cpp/component/keyple-calypso/src/main/transaction/exception/CalypsoPoCloseSecureSessionException.h:55:73: warning: reference to local variable ‘e’ returned [-Wreturn-local-addr]
   55 |         return std::move(reinterpret_cast<CalypsoPoCommandException&>(e));
      |                                                                         ^
/home/XXXX/keyple-cpp/component/keyple-calypso/src/main/transaction/exception/CalypsoPoCloseSecureSessionException.h:54:24: note: declared here
   54 |         std::exception e = CalypsoPoTransactionException::getCause();**

How can i fix this error?
Thanks

**Comment by jeanpierrefortune** [comment]
Hi,
If you start a new Keyple C++ project, I strongly recommend you to switch to version 2.0, this repository is not maintained anymore!

We have started a tutorial that should make it easier to start the project, it can be seen here: https://keyple.org/learn/build-your-first-app/cpp-app/

However, do not hesitate to submit the difficulties you encounter either via a GitHub issue in the appropriate repository like here or via the mailing list [keyple-dev](https://accounts.eclipse.org/mailing-list/keyple-dev).

Hope this helps!

**Comment by kadirkidir1** [comment]
Thanks for answer.

But i can not open localhost address. Can you help me?

Thanks again.

**Comment by jeanpierrefortune** [comment]
Oops, I'm sorry, I copied the development URL by mistake!
I have corrected the message.
